# Generated by Django 2.2 on 2019-04-13 08:45

import ags_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0003_auto_20190410_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='walker',
            name='walking_map',
            field=models.ImageField(blank=True, upload_to=ags_site.models.user_directory_path, verbose_name='Карта выгула'),
        ),
    ]
