# Generated by Django 2.2 on 2019-04-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0006_walkingdate_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkingdate',
            old_name='street',
            new_name='address',
        ),
    ]
