# Generated by Django 2.2 on 2019-04-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0007_auto_20190417_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkingdate',
            name='type',
            field=models.CharField(choices=[('C', 'Классический'), ('A', 'Активный')], default='C', max_length=30, verbose_name='Тип прогулки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='walkingdate',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='Адрес владельца'),
        ),
        migrations.AlterField(
            model_name='walkingdate',
            name='breed',
            field=models.CharField(blank=True, max_length=30, verbose_name='Порода собаки'),
        ),
        migrations.AlterField(
            model_name='walkingdate',
            name='dog_owner_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Владелец собаки'),
        ),
    ]
