# Generated by Django 2.2 on 2019-04-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0010_auto_20190428_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
