# Generated by Django 2.2 on 2019-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0012_auto_20190428_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproductcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, default='ags_site/media/default.png', max_length=30, upload_to='', verbose_name='Обложка категории'),
        ),
        migrations.AlterField(
            model_name='shopproductcategory',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название категории'),
        ),
    ]
