# Generated by Django 2.2 on 2019-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0005_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkingdate',
            name='breed',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
