# Generated by Django 2.2 on 2019-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0008_auto_20190418_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='Video',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.CharField(blank=True, max_length=30, verbose_name='Категория товара'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image_1',
            field=models.ImageField(blank=True, max_length=30, upload_to='', verbose_name='Первое изображение'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image_2',
            field=models.ImageField(blank=True, max_length=30, upload_to='', verbose_name='Второе изображение'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image_3',
            field=models.ImageField(blank=True, max_length=30, upload_to='', verbose_name='Третье изображение'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='thumbnail',
            field=models.ImageField(default='ags_site/media/default.png', max_length=30, upload_to='', verbose_name='Обложка товара'),
        ),
    ]
