# Generated by Django 2.2 on 2019-04-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0011_auto_20190428_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopproductcategory',
            options={'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='walker',
            options={'verbose_name': 'Волкер', 'verbose_name_plural': 'Волкеры'},
        ),
        migrations.AlterModelOptions(
            name='walkingdate',
            options={'verbose_name': 'Выгул', 'verbose_name_plural': 'Выгулы'},
        ),
        migrations.AlterModelOptions(
            name='walkingzone',
            options={'verbose_name': 'Зона выгула(район)', 'verbose_name_plural': 'Зоны выгула(районы)'},
        ),
    ]
