# Generated by Django 2.2 on 2019-04-28 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0015_walker_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductcategory',
            name='url_title',
            field=models.CharField(default='default', max_length=30, validators=[django.core.validators.RegexValidator(message='Имя должно состоять из латинских букв и знаков подчёркивания', regex='^[a-zA-Z_]+$')], verbose_name='Имя в адресе страницы'),
            preserve_default=False,
        ),
    ]
