# Generated by Django 2.2 on 2019-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ags_site', '0016_shopproductcategory_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to='', verbose_name='Обложка товара'),
        ),
    ]
